
# --- PDM config --------------------------------------------- #
[project]
name = "PBG Bear"
version = "0.1.0"
description = "PBG Python template collection"
authors = [
    {name = "PBG", email = "pythonbiellagroup@gmail.com"},
]
dependencies = [
    "detect-secrets>=1.4.0",
    "ecs-logging>=2.0.0",
    "loguru>=0.6.0",
    "pyaml>=21.10.1",
    "pydantic>=1.10.4",
    "python-dotenv>=0.21.0",
    "Unidecode>=1.3.6",
]
requires-python = ">=3.9.8,<3.11.1"
license = {text = "MIT"}
classifiers = ["Topic :: Cookiecutter", "Topic :: Template", "Topic :: Python", "Topic :: App"]

[project.urls]
homepage = "https://pythonbiellagroup.it"
repository = "https://github.com/PythonBiellaGroup/Bear"
documentation = ""

[tool.pdm.build]
includes = []

[[tool.pdm.source]]
name = "pypi.org"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.dev-dependencies]
dev = [
    "autoflake>=2.0.0",
    "autopep8>=2.0.1",
    "bandit>=1.7.4",
    "black>=22.12.0",
    "commitizen>=2.39.1",
    "cookiecutter<3.0.0,>=2.1.1",
    "deptry>=0.7.1",
    "flake8-bandit>=4.1.1",
    "flake8-builtins>=2.1.0",
    "flake8-isort>=6.0.0",
    "flake8>=6.0.0",
    "ipython>=8.8.0",
    "jupyter>=1.0.0",
    "mypy>=0.991",
    "pre-commit>=2.21.0",
    "pylint>=2.15.9",
    "pytest-cov>=4.0.0",
    "pytest>=6.2.5",
    "ruff>=0.0.213",
    "types-PyYAML>=6.0.12.2",
    "types-requests>=2.28.11.7",
    "types-urllib3>=1.26.25.4",
]
docs = [
    "mkdocs>=1.4.2",
    "mkdocs-autorefs>=0.4.1",
    "mkdocs-gallery>=0.7.6",
    "mkdocs-jupyter>=0.22.0",
    "mkdocs-macros-plugin>=0.7.0",
    "mkdocs-material>=8.5.11",
    "mkdocs-minify-plugin>=0.6.2",
    "mkdocs-redirects>=1.2.0",
    "mkdocstrings>=0.20.0",
]